FROM maven:3.9-eclipse-temurin-21
WORKDIR /app

# Pré-charger les deps (accélère le premier run)
COPY ../pom.xml /app/pom.xml
RUN mvn -q -DskipTests dependency:go-offline

# Le code sera monté par Compose
EXPOSE 8080
CMD ["mvn","-q","-DskipTests","spring-boot:run"]